project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  #  browser: false
  render:
    - "*.qmd"
extensions:
  fontawesome: true
website:
  title: "Записки домашнего родослова"
  site-url: "https://eryxspp.github.io/VM/"
  # subtitle: "Возвращая из забвения, дарю бессмертие…"
  # author: "Владислав Веденеев"
  search:
    location: navbar
    type: overlay
  # announcement: 
  #   content: "Возвращая из забвения, дарю бессмертие…" 
  #   position: below-navbar 
  favicon: _static/favicon.ico
  page-footer:
    right: "© 2026, В.Д. Веденеев, Д.Д. Саякин"   
    background: light
  navbar:
    left:
    - icon: house
      href: /
    - icon: list-check
      text: " "
      href: fn.qmd
    - icon: calendar2-check
      text: " "
      href: dates.qmd
    - icon: file-earmark-richtext
      text: Статьи
      menu: 
      - text: Легенда №6 по улице Щепкина
        href: Статьи/Легенда № 6/
      
  #     - href: Батищевы/index.qmd
  #       text: Батищевы
#      - about.qmd
  sidebar:
    style: floating
    background: light
    contents:
      - icon: house
        text: Об этом сайте
        href: index.qmd
      - icon: list-check
        text: Фамилии
        href: fn.qmd
      - icon: calendar2-check
        text: Даты
        href: dates.qmd
      - section: Статьи
        icon: file-earmark-richtext
        contents:
          - text: Легенда №6 по улице Щепкина
            href: Статьи/Легенда № 6/

format:
  html:
    default-image-extension: png
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full
    code-fold: show
    mermaid:
      theme: neutral
  #    securityLevel: 'loose'
  # typst:
  #   keep-typ: true
  #   papersize: a4
  #   toc: true
  #   number-depth: 2
  #   section-numbering: 1.1.a
  #   columns: 1
  #   default-image-extension: png
  #   mermaid:
  #     theme: neutral
  #   logo: 
  #     width: 1in
  #     location: right-top
  #     padding-right: 0.5in
  #     padding-top: 0.25in
  #     alt: Alternate alternate text
      
  # pdf:
  #   default-image-extension: png
  #   mermaid:
  #     theme: neutral

execute:
  echo: false

jupyter: python3
