---
title: "Наши фамилии"
---

## Абрамовы
- Борис,
- Виталий Борисович,
- Полина Витальевна

## Барабаш
- Людмила Сергеевна,
- Анастасия Александровна

## [Батищевы](/Батищевы/index.qmd)
- [Василий Иванович](/Батищевы/Василий_Иванович),
- [Антонина Яковлевна](/Батищевы/Антонина_Яковлевна),
- [Галина Васильевна](/Батищевы/Галина_Васильевна),
- [Екатерина Васильевна](/Батищевы/Екатерина_Васильевна),
- [Надежда Васильевна](/Батищевы/Надежда_Васильевна)

## Бахтемировы
- Андрей Иванович,
- Мария Николаевна,
- Константин Андреевич,
- Михаил Андреевич,
- Иван Андреевич,
- Николай Андреевич,
- Павел   Андреевич,
- Александр Андреевич,
- Сергей Андреевич,
- Мария Андреевна,
- Елизавета Андреевна

## [Безверхние](/img/schemes/Levykiny_shema.pdf):
- Вилен Николаевич,
- Наталья Николаевна,
- Олег Виленович

## Беляевы
- Степан Иванович,
- Александра Захаровна,
- [Иван Степанович](/Беляевы/Иван_Степанович),
- [Анастасия Михайловна](/Беляевы/Анастасия_Михайловна),
- Александр Степанович,
- Пелагея Тимофеевна,
- Мария Степановна,
- Наталья Степановна,
- Михаил Степанович,
- Александра,
- Галина Михайловна,
- Василий Степанович,
- Зоя Васильевна,
- Анатолий Васильевич,
- [Анна Ивановна](/Беляевы/Анна_Ивановна),
- [Виталий Иванович](/Беляевы/Виталий_Иванович),
- Валерий Витальевич,
- [Агния Ивановна](/Беляевы/Агния_Ивановна),
- Александра Ивановна,
- Пётр Иванович,
- [Александр Иванович](/Беляевы/Александр_Иванович),
- Сергей Александрович,
- Михаил Александрович,
- [Аркадий Иванович](/Беляевы/Аркадий_Иванович),
- Злата Алексеевна,
- Алексей Аркадьевич,
- Лидия Алексеевна,
- Антон Сергеевич,
- Евгения Сергеевна,
- Иван Михайлович,
- Александр Михайлович,
- Елена Алексеевна

## Буткевичи
- Фридрих Александрович,
- Наталия Фридриховна

## Бутт
- [Галина Васильевна](/Батищевы/Галина_Васильевна)

## Васильковы
- Иван Георгиевич,
- Евгения Владимировна,
- Михаил Иванович,
- Иван Михайлович

## Веденеевы
- [Василий Афанасьевич](/Веденеевы/Василий_Афанасьевич),
- [Анисия Павловна](/Веденеевы/Анисия_Павловна),
- [Василий Васильевич](/Веденеевы/Василий_Васильевич),
- [Валентина Спиридоновна](/Веденеевы/Валентина_Спиридоновна),
- [Анна Васильевна](/Веденеевы/Анна_Васильевна),
- [Элеонора Васильевна](/Веденеевы/Элеонора_Васильевна),
- [Владислав Дмитриевич](/Веденеевы/Владислав_Дмитриевич),
- [Максим Владиславович](/Веденеевы/Максим_Владиславович),
- [Мария Владиславовна](/Веденеевы/Мария_Владиславовна)

## Веригины
- Иван Фёдорович,
- Мария Ильинична,
- [Алексей Иванович](index.php?option=com_content&view=article&id=4:veriginaliv&catid=9:nashi-lyudi&Itemid=104),
- [Юлия Сергеевна](index.php?option=com_content&view=article&id=6:veriginayulserg&catid=9:nashi-lyudi&Itemid=104),
- Мария Ивановна,
- [Надежда Алексеевна](index.php?option=com_content&view=article&id=7:veriginanadal&catid=9:nashi-lyudi&Itemid=104),
- [Владимир Алексеевич](index.php?option=com_content&view=article&id=5:veriginvlal&catid=9:nashi-lyudi&Itemid=104),
- [Зинаида Александровна](index.php?option=com_content&view=article&id=8:veriginazinalex&catid=9:nashi-lyudi&Itemid=104),
- [Галина Владимировна](index.php?option=com_content&view=article&id=50:veriginagalvl&catid=9:nashi-lyudi&Itemid=104),
- [Кира Владимировна](index.php?option=com_content&view=article&id=11:veriginakirvl&catid=9:nashi-lyudi&Itemid=104),
- Юлия Алексеевна,
- Мария Алексеевна,
- Сергей Алексеевич,
- [Василий Алексеевич](index.php?option=com_content&view=article&id=9:veriginvasal&catid=9:nashi-lyudi&Itemid=104),
- [Софья Алексеевна](index.php?option=com_content&view=article&id=10:levykinasofal&catid=9:nashi-lyudi&Itemid=104)
- [Виктор Иванович](index.php?option=com_content&view=article&id=44:veriginviktiv&catid=9:nashi-lyudi&Itemid=104),
- Елизавета Самсоновна,
- Варвара Викторовна,
- Екатерина Викторовна

## Гаусман
- Валентин,
- Татьяна Алексеевна,
- Юрий Валентинович

## Гуревичи
- [Арсений Владиславович](index.php?option=com_content&view=article&id=33:gurevicharsvlad&catid=9:nashi-lyudi&Itemid=104),
- [Леонид Владиславович](index.php?option=com_content&view=article&id=34:gurevichleovlad&catid=9:nashi-lyudi&Itemid=104)

## Гуреевы
- Анна Александровна
- Валентина Владимировна

## Давыдовы
- Ольга Владимировна

## Дудниковы
- Алексей Тимофеевич,
- Александра Васильевна,
- Лидия Алексеевна

## Ивановы
- Ольга Фёдоровна

## Иларионовы
- Самсон,
- Елена Михайловна,
- Анна Самсоновна,
- Мария Самсоновна,
- Ирина Егоровна,
- Николай Самсонович,
- Елизавента Самсоновна,
- Мария Самсоновна,
- Агния Самсоновна,
- Сергей Самсонович,
- Александр Самсонович,
- Надежда Самсоновна,
- Александр Самсонович

## Камышаловы
- Лариса Сергеевна,
- Станислав Владимирович

## Киселёвы
- Юлия Николаевна

## Климановы
- Максим Данилович,
- Наталья Павловна,
- Агриппина Максимовна

## Козловы
- Вера Владимировна

## Комаровы
- Алексей Иванович,
- [Ирина Александровна](index.php?option=com_content&view=article&id=15:komarovairalex&catid=9:nashi-lyudi&Itemid=104),
- Елена Алексеевна

## Крыловы
- Сергей Дмитриевич,
- Мария Борисовна,
- Мария Сергеевна

## [Кудрявцевы](/img/schemes/Levykiny_shema.pdf)
- Константин Дмитриевич,
- Анна Васильевна,
- Константин Константинович,
- Эстер Хацкелевна,
- Геннадий Константинович

## Кузнецовы
- Валентин,
- Елена Владимировна,
- Юрий Валентинович,
- Виктор Валентинович,
- Наталья Викторовна,
- Сергей Викторович

## Кумровы
- Ольга Николаевна

## [Левыкины](/Левыкины/Levykiny_shema.pdf)
- [Василий Михайлович](/Левыкины/Василий_Михайлович),
- Александра Семёновна,
- Владимир Васильевич,
- Николай Васильевич,
- [Софья Алексеевна](/Левыкины/Софья_Алексеевна),
- Татьяна Николаевна,
- Виталий Васильевич,
- Василий Васильевич,
- Гурий Васильевич,
- Нина Васильевна,
- Анна Васильевна

## Лясковские
- [Агния Владимировна](index.php?option=com_content&view=article&id=23:lyaskovskayaagvl&catid=9:nashi-lyudi&Itemid=104),
- [Екатерина Олеговна](index.php?option=com_content&view=article&id=29:lyaskovskayaekole&catid=9:nashi-lyudi&Itemid=104)

## [Михайловские](img/schemes/Levykiny_shema.pdf)
- Александр Александрович,
- Татьяна Николаевна,
- Лидия Александровна

## Нестеровичи
- Иван Францевич,
- Сергей Францевич,
- [Евфимия Францевна](index.php?option=com_content&view=article&id=16:nesterovichevffr&catid=9:nashi-lyudi&Itemid=104),
- [Александр Алексеевич](index.php?option=com_content&view=article&id=13:nesterovichalexal&catid=9:nashi-lyudi&Itemid=104),
- Татьяна Алексеевна,
- Владимир Алексеевич,
- Елена Владимировна,
- [Людмила Александровна](index.php?option=com_content&view=article&id=14:sayakinlyudalex&catid=9:nashi-lyudi&Itemid=104),
- [Ирина Александровна](index.php?option=com_content&view=article&id=15:komarovairalex&catid=9:nashi-lyudi&Itemid=104),
- Валентина Владимировна,
- Владимир Александрович,
- Галина Петровна,
- Наталья Васильевна,
- Евгений Александрович,
- Татьяна Александровна,
- Сергей Юрьевич,
- Александра Сергеевна,
- Александр Евгеньевич,
- Екатерина Александровна,
- [Михаил Евгеньевич](index.php?option=com_content&view=article&id=38:nesterovichmihevg&catid=9:nashi-lyudi&Itemid=104),
- Ольга Фёдоровна,
- [Михаил Михайлович](index.php?option=com_content&view=article&id=39:nesterovichmikhmikh&catid=9:nashi-lyudi&Itemid=104),
- Галина Евгеньевна

## Николаевы
- Александр Николаевич,
- Авдотья Васильевна,
- Сергей Александрович,
- Александра Васильевна,
- Пётр Александрович,
- Василий Сергеевич,
- Надежда Сергеевна,
- [Юлия Сергеевна](index.php?option=com_content&view=article&id=6:veriginayulserg&catid=9:nashi-lyudi&Itemid=104)

## Ореховы
- Александра Николаевна

## [Плущевские](img/schemes/Levykiny_shema.pdf)
- Николай Петрович,
- Нина Васильевна,
- Наталья Николаевна,
- Анатолий Николаевич

## Подобаевы
- Тимофей Александрович,
- Вера Владимировна,
- Василиса Тимофеевна,
- Василий Тимофеевич

## Пучковы
-  Татьяна Владимировна,
- Борис,
- Валерия Борисовна

## Руденко
- [Валентина Спиридоновна](/Веденеевы/Валентина_Спиридоновна) [26 ]

## Савины
- [Владимир Григорьевич](/Савины/Владимир_Григорьевич), [27]
- [Марина Ивановна](/Савины/Марина_Ивановна), [28]
- Михаил Владимирович,
- Вера Владимировна

## Саякины
- Иван Евдокимович,
- Наталья Ивановна,
- Полина Ивановна,
- [Григорий Иванович](/Саякины/Григорий_Иванович), [17]
- [Людмила Александровна](index.php?option=com_content&view=article&id=14:sayakinlyudalex&catid=9:nashi-lyudi&Itemid=104),
- Валентина Ивановна,
- Анна Ивановна,
- [Владимир Григорьевич](/Савины/Владимир_Григорьевич), [27]
- [Дмитрий Григорьевич](/Саякины/Дмитрий_Григорьевич), [19]
- [Элеонора Васильевна](index.php?option=com_content&view=article&id=20:sayakinaelvas&catid=9:nashi-lyudi&Itemid=104),
- [Дмитрий Дмитриевич](index.php?option=com_content&view=article&id=21:sayakindmdm&catid=9:nashi-lyudi&Itemid=104),
- Наталия Фридриховна,
- [Владислав Дмитриевич](/Веденеевы/Владислав_Дмитриевич) [22]

## Сипотовские
- Карп Семёнович,
- Праскева Карповна,
- Анна Карповна,
- Иван Карпович,
- Василий Карпович,
- Андрей Карпович,
- Мария Андреевна,
- Владимир Андреевич,
- Любовь Фёдоровна,
- Борис Владимирович,
- Елена Владимировна,
- Татьяна Владимировна

## Соловьёвы
- Анна Ивановна,
- Серёжа,
- Галина Дмитриевна,
- Ирина Дмитриевна

## Сургучёвы
- Яков Григорьевич,
- Дарья Михайловна,
- Антонина Яковлевна

## Томковичи
- Пётр Михайлович,
- Полина Ивановна,
- Герард Петрович,
- Ирина Борисовна,
- Ольга Герардовна,
- Валентин Петрович,
- Надежда Валентиновна

## Трушины
- Василий Павлович,
- Агриппина Максимовна,
- Виктор Васильевич,
- Зинаида Васильевна,
- Наталья Васильевна

## Филипович
- [Надежда Алексеевна](/Веригины/Надежда_Алексеевна/index.qmd) 7,
- Николай Алексеевич,
- Павел Алексеевич,
- Екатерина Викторовна

## Фроловы
- Павел Фролович,
- Татьяна Лукинична,
- Наталья Павловна,
- Иван Павлович,
- Анна Ивановна,
- Василий Иванович,
- Александра Николаевна,
- Анатолий Васильевич,
- Татьяна Васильевна

## [Хребтовы](/Хребтовы/index.qmd)
- [Анатолий Иванович](/Хребтовы/Анатолий_Иванович/index.qmd),
- [Агния Ивановна](/Хребтовы/Агния_Ивановна/index.qmd) 31,
- [Владимир Анатольевич](/Хребтовы/Владимир_Анатольевич/index.qmd) 35,
- [Екатерина Васильевна](/Хребтовы/Екатерина_Васильевна/index.qmd) 36,
- [Агния Владимировна](/Хребтовы/Агния_Владимировна/index.qmd) 23,
- [Наталья Владимировна](/Хребтовы/Наталья_Владимировна/index.qmd) 32

## Чекомасовы
- Татьяна Васильевна,
- Михаил Александрович

## Чижовы
- Владимир,
- Зоя Ивановна,
- Сергей Владимирович,
- Галина Парфёновна,
- Людмила Сергеевна,
- Наталья Сергеевна

## Шипорины
- Валентина Ивановна,
- Вячеслав Владимирович,
- Лидия

## Швогер-Летецкие
- Людвиг Антонович,
- Петр Антонович,
- Анатолий Антонович,
- Варвара Викторовна,
- Анатолий Анатольевич

## Щербаковы
- Роман Вячеславович,
- Галина Евгеньевна,
- Василий Романович,
- Данила Романович,
- Елизавета Романовна

## Ясинчук
- [Надежда Васильевна](/Батищевы/Надежда_Васильевна)

## Яфа
- Александр Фёдорович,
- Софья Петровна,
- [Зинаида Александровна](index.php?option=com_content&view=article&id=8:veriginazinalex&catid=9:nashi-lyudi&Itemid=104),
- Александр Александрович,
- Нина Александровна,
- Ольга Александровна,
- Константин Александрович.
